apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "finder.fullname" . }}-worker
  annotations:
    kubernetes.io/ingress.class: "gce-interal"
    ingress.gcp.kubernetes.io/pre-shared-cert: "klaytnfinder-dev"
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/v1beta1.FrontendConfig: "http-to-https"
spec:
  rules:
    - host: {{ .Values.worker.host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /api*
            backend:
              service:
                name: {{ include "finder.fullname" . }}-worker
                port:
                  number: 8080