global:
  nameOverride: finder
  projectId: klaytn-finder
  network:
  #[baobab, cypress]
  profile:
  #[stag, prod]
  domain:
  serviceAccountName: sa-finder-service
  namespace: finder

api:
  front:
    images:
      repository: asia-northeast3-docker.pkg.dev/klaytn-finder/finder-prod/finder-api
      tag: public-283aef52a30e4d1195b8661aba02654edc524b7c
    replicas: 1
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
  papi:
    images:
      repository: asia-northeast3-docker.pkg.dev/klaytn-finder/finder-prod/finder-api
      tag: public-6d20e18b8bf50aeec78119747a4192271f2bfb19
    replicas: 1
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
  oapi:
    images:
      repository: asia-northeast3-docker.pkg.dev/klaytn-finder/finder-prod/finder-oapi
      tag: public-e900b0251cbb0e3375224ad70ce24ea2fec5ebf0
    replicas: 1
    resources:
      requests:
        cpu: 2000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 2Gi

worker:
  enabled: false
  images:
    repository: asia-northeast3-docker.pkg.dev/klaytn-finder/finder-prod/finder-worker
    tag: public-283aef52a30e4d1195b8661aba02654edc524b7c
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi

compiler:
  enabled: false
  images:
    repository: asia-northeast3-docker.pkg.dev/klaytn-finder/finder-prod/finder-compiler-api
    tag: public-283aef52a30e4d1195b8661aba02654edc524b7c
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
