global:
  nameOverride: finder
  network:
  #[baobab, cypress]
  profile:
  #[dev, stag, prod]

  serviceAccountName:
  namespace:
  serviceAccountRoleArn:

secretManager:
  REGION:
  ARN:

s3:
  AWS_S3_REGION:
  AWS_S3_PRIVATE_BUCKET:
  AWS_S3_PUBLIC_BUCKET:

cdn:
  URL:

chain:
  CAVER_CYPRESS_RPC_ENDPOINT:
  CAVER_BAOBAB_RPC_ENDPOINT:

datbaseEndpoint:
  MYSQL_CYPRESS_01_ENDPOINT:
  MYSQL_BAOBAB_01_ENDPOINT:
  MYSQL_CYPRESS_0201_ENDPOINT:
  MYSQL_CYPRESS_0202_ENDPOINT:
  MYSQL_CYPRESS_0203_ENDPOINT:
  MYSQL_CYPRESS_0204_ENDPOINT:
  MYSQL_CYPRESS_0205_ENDPOINT:
  MYSQL_BAOBAB_02_ENDPOINT:
  MYSQL_CYPRESS_03_ENDPOINT:
  MYSQL_BAOBAB_03_ENDPOINT:
  MYSQL_COMMON_ENDPOINT:

apiKeys:
  CMC_PRO_API_KEY:

openSearch:
  OPEN_SEARCH_URL:

redis:
  REDIS_ENDPOINT:

zookeeper:
  ZOOKEEPER_ENDPOINT:

apiEndpoint:
  COMPILER_API_ENDPOINT:
  PAPI_API_CYPRESS_ENDPOINT:
  PAPI_API_BAOBAB_ENDPOINT:

api:
  front:
    ingress: #alb.ingress.kubernetes.io/group.name
    images:
      repository: public.ecr.aws/y1e5c4k9/finder-api
      tag: public-3b7017c3c578da343833d6d6d7a070517e700fbb
    host:
    replicas: 1
    env:
      - name: SPRING_PROFILES_ACTIVE
        value:
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
  papi:
    images:
      repository: public.ecr.aws/y1e5c4k9/finder-api
      tag: public-3b7017c3c578da343833d6d6d7a070517e700fbb
    host:
    replicas: 1
    env:
      - name: SPRING_PROFILES_ACTIVE
        value:
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
  oapi:
    images:
      repository: public.ecr.aws/y1e5c4k9/finder-oapi
      tag: public-06-d873c1e4b5760469a43918edd22ea17336b36db8
    host:
    replicas: 1
    env:
      - name: SPRING_PROFILES_ACTIVE
        value:
    resources:
      requests:
        cpu: 2000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 2Gi

worker:
  enabled: false
  images:
    repository: public.ecr.aws/y1e5c4k9/finder-worker
    tag: public-f2b304db44dfada6d3d006b11c807f3ceb125b17
  host:
  replicas: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value:
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi

compiler:
  enabled: false
  images:
    repository: public.ecr.aws/y1e5c4k9/finder-compiler
    tag: public-3b7017c3c578da343833d6d6d7a070517e700fbb
  host:
  replicas: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value:
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
