apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "finder.fullname" . }}-papi
  name: {{ include "finder.fullname" . }}-papi
spec:
  ports:
    - name: "8080-8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ include "finder.fullname" . }}-papi
  type: ClusterIP