apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finder.fullname" . }}-compiler
spec:
  selector:
    matchLabels:
      app: {{ include "finder.fullname" . }}-compiler
  replicas: {{ .Values.compiler.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ include "finder.fullname" . }}-compiler
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      terminationGracePeriodSeconds: 60
      tolerations:
        - key: "type"
          value: "finder-node-pool"
          effect: "NoSchedule"
      containers:
        - name: {{ include "finder.fullname" . }}-compiler
          image: "{{ .Values.compiler.images.repository }}:{{ .Values.compiler.images.tag }}"
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 40"]
          envFrom:
            - secretRef:
                name: finder-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: JAVA_OPTS
              value: -Xms1G -Xmx1G

          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.compiler.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3