apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "finder.fullname" . }}-compiler
  annotations:
    kubernetes.io/ingress.class: "gce-interal"
    ingress.gcp.kubernetes.io/pre-shared-cert: "klaytnfinder-net"
    networking.gke.io/v1beta1.FrontendConfig: "http-to-https"
spec:
  rules:
    - host: compiler-api.{{ .Values.global.domain }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "finder.fullname" . }}-compiler
                port:
                  number: 8080