apiVersion: v1
kind: Service
metadata:
  labels:
    app:  finder-compiler
  name:  finder-compiler
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app:  finder-compiler