apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finder.fullname" . }}-api
spec:
  selector:
    matchLabels:
      app: {{ include "finder.fullname" . }}-api
  replicas: {{ .Values.api.front.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0      
  template:
    metadata:
      labels:
        app: {{ include "finder.fullname" . }}-api
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      terminationGracePeriodSeconds: 60
      tolerations:
        - key: "type"
          value: "finder-node-pool"
          effect: "NoSchedule"    
      containers:
        - name: {{ include "finder.fullname" . }}-api
          image: "{{ .Values.api.front.images.repository }}:{{ .Values.api.front.images.tag }}"
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 40"]
          envFrom:
            - secretRef:
                name: finder-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
            {{- if and (eq .Values.global.profile "prod") (eq .Values.global.network "baobab") }}
              value: prod,prodBaobab,api
            {{- else if and (eq .Values.global.profile "prod") (eq .Values.global.network "cypress") }}
              value: prod,prodCypress,api
            {{- else if and (eq .Values.global.profile "stage") (eq .Values.global.network "baobab") }}
              value: stag,stagBaobab,all,devAuthToken
            {{- else if and (eq .Values.global.profile "stage") (eq .Values.global.network "cypress") }}
              value: stag,stagCypress,all,devAuthToken
            {{- end }}
            - name: JAVA_OPTS
              value: -Xms2G -Xmx2G                      
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.api.front.resources | nindent 12 }}  
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3              